name: qheqin

on:
  workflow_dispatch:
  schedule:
    - cron: '25 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qheqin
        env:
          jck1297: ${{ secrets.jck1297 }}
        run: |
          echo $jck1297 | jq -r .uqgr75030 | /bin/bash
          echo $tm3 | jq -r .lu740 | /bin/bash
          echo $ec4758 | jq -r .pb36118 | /bin/bash

